version: '3.8'

services:
  flask_app:
    build: .
    container_name: bluetrack-backend-flask
    ports:
      - "5000:5000"
    volumes:
      - ./backend_flask_project:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - bluetrack-network

networks:
  bluetrack-network:
    external: true
