"""removed is_registered

Revision ID: 7a10837fa9e2
Revises: 920817951e0b
Create Date: 2024-09-30 14:30:37.975690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a10837fa9e2'
down_revision = '920817951e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msstudent', schema=None) as batch_op:
        batch_op.drop_column('is_registered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msstudent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_registered', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
